### PR TITLE
SCT-282: Removed exported bool DoFnInvoked that was not explicitly threadsafe

### PR DESCRIPTION
**Pull request by JaySmithWpg**
Go's race condition detector is hostile towards publicly exported values that are directly written to from multiple threads. This causes issues when testing projects that use this package. Accessor methods are preferred for exported values, but in this case the value is unused across our code base and can be safely removed.

### CODE REVIEW

**Comment by JaySmithWpg** [comment]
After realising that this package is public to more than just SSO, I've rethought my approach. Using sync.Once to prevent race conditions on the write, without changing anything the package exports.

**Comment by rikonor** [comment]
@JaySmithWpg It's true that this is a public package, but that said we don't really have need for this `Invoke` flag (it can be implemented very easily in tests without polluting with additional fields). We can just bump the major version to make sure we're not breaking anything for anyone.

**Comment by JaySmithWpg** [comment]
@rikonor Agreed on all counts. However, before we bump to the next major version and completely rip it out, we should leave our version 2 users with the gift of conditional thread safety :smile:

**Comment by rikonor** [comment]
Yea, that's a good point.

**Pull request merged**
